<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxwqBkJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxwqBkJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxwqBkJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxwqBkJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTxwqBkJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'TxwqBkJ',
    'container.build_id' => '5e8b0ca8',
    'container.build_time' => 1674609632,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxwqBkJ');
