<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBlwwpih\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBlwwpih/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBlwwpih.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBlwwpih\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBlwwpih\App_KernelDevDebugContainer([
    'container.build_hash' => 'Blwwpih',
    'container.build_id' => '073fdd91',
    'container.build_time' => 1674429528,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBlwwpih');
