<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU7JmvC0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU7JmvC0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU7JmvC0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU7JmvC0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU7JmvC0\App_KernelDevDebugContainer([
    'container.build_hash' => 'U7JmvC0',
    'container.build_id' => '9ec8af17',
    'container.build_time' => 1674767764,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU7JmvC0');
