<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S6Sx6SGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s6Sx6SG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s6Sx6SG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blocRepository' => ['privates', 'App\\Repository\\SkillBlocRepository', 'getSkillBlocRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
            'ueRepository' => ['privates', 'App\\Repository\\UeRepository', 'getUeRepositoryService', true],
        ], [
            'blocRepository' => 'App\\Repository\\SkillBlocRepository',
            'em' => '?',
            'studentRepository' => 'App\\Repository\\StudentRepository',
            'ueRepository' => 'App\\Repository\\UeRepository',
        ]);
    }
}
