<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P7b4e3kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P7b4e3k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P7b4e3k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'student' => ['privates', '.errored..service_locator.P7b4e3k.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.P7b4e3k": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'student' => 'App\\Entity\\User',
            'studentRepository' => 'App\\Repository\\StudentRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
