<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y2pEjzOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y2pEjzO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y2pEjzO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'skillBloc' => ['privates', '.errored..service_locator.Y2pEjzO.App\\Entity\\SkillBloc', NULL, 'Cannot autowire service ".service_locator.Y2pEjzO": it needs an instance of "App\\Entity\\SkillBloc" but this type has been excluded in "config/services.yaml".'],
            'ueRepository' => ['privates', 'App\\Repository\\UeRepository', 'getUeRepositoryService', true],
        ], [
            'skillBloc' => 'App\\Entity\\SkillBloc',
            'ueRepository' => 'App\\Repository\\UeRepository',
        ]);
    }
}
