<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HDNOYOXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hDNOYOX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hDNOYOX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotion' => ['privates', '.errored.PDFDHhn', NULL, 'Cannot determine controller argument for "App\\Controller\\StudentController::choiceMade()": the $promotion argument is type-hinted with the non-existent class or interface: "App\\Entity\\Promotion".'],
            'student' => ['privates', '.errored..service_locator.hDNOYOX.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.hDNOYOX": it needs an instance of "App\\Entity\\Student" but this type has been excluded in "config/services.yaml".'],
            'ueRepository' => ['privates', 'App\\Repository\\UeRepository', 'getUeRepositoryService', true],
        ], [
            'promotion' => '?',
            'student' => 'App\\Entity\\Student',
            'ueRepository' => 'App\\Repository\\UeRepository',
        ]);
    }
}
