<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EYzEkCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EYzEkC_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EYzEkC_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encryptor' => ['privates', 'SpecShaper\\EncryptBundle\\Encryptors\\EncryptorInterface', 'getEncryptorInterfaceService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'encryptor' => 'SpecShaper\\EncryptBundle\\Encryptors\\EncryptorInterface',
            'passwordHasher' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
