<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZHxMd2DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZHxMd2D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZHxMd2D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotion' => ['privates', '.errored.NmKmI10', NULL, 'Cannot determine controller argument for "App\\Controller\\PromotionController::delete()": the $promotion argument is type-hinted with the non-existent class or interface: "App\\Entity\\Promotion".'],
            'promotionRepository' => ['privates', '.errored.gGQdwih', NULL, 'Cannot determine controller argument for "App\\Controller\\PromotionController::delete()": the $promotionRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PromotionRepository".'],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'promotion' => '?',
            'promotionRepository' => '?',
            'studentRepository' => 'App\\Repository\\StudentRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
