<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X628au0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X628au0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X628au0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'encryptor' => ['privates', 'SpecShaper\\EncryptBundle\\Encryptors\\EncryptorInterface', 'getEncryptorInterfaceService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'promotion' => ['privates', '.errored.uj3S6jY', NULL, 'Cannot determine controller argument for "App\\Controller\\StudentController::upload()": the $promotion argument is type-hinted with the non-existent class or interface: "App\\Entity\\Promotion".'],
        ], [
            'em' => '?',
            'encryptor' => 'SpecShaper\\EncryptBundle\\Encryptors\\EncryptorInterface',
            'passwordHasher' => '?',
            'promotion' => '?',
        ]);
    }
}
