<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PDFDHhnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.PDFDHhn' shared service.
     *
     * @return \App\Entity\Promotion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\StudentController::choiceMade()": the $promotion argument is type-hinted with the non-existent class or interface: "App\\Entity\\Promotion".');
    }
}
