<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QD1nIwgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QD1nIwg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QD1nIwg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'parcour' => ['privates', '.errored..service_locator.QD1nIwg.App\\Entity\\Parcour', NULL, 'Cannot autowire service ".service_locator.QD1nIwg": it needs an instance of "App\\Entity\\Parcour" but this type has been excluded in "config/services.yaml".'],
            'parcourRepository' => ['privates', 'App\\Repository\\ParcourRepository', 'getParcourRepositoryService', true],
        ], [
            'parcour' => 'App\\Entity\\Parcour',
            'parcourRepository' => 'App\\Repository\\ParcourRepository',
        ]);
    }
}
