<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FWxCbWfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fWxCbWf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fWxCbWf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'promotionRepository' => ['privates', '.errored.o8HUO3E', NULL, 'Cannot determine controller argument for "App\\Controller\\PromotionController::index()": the $promotionRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PromotionRepository".'],
        ], [
            'em' => '?',
            'promotionRepository' => '?',
        ]);
    }
}
