<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AkaK8xCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AkaK8xC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AkaK8xC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotion' => ['privates', '.errored.Y2ew4ww', NULL, 'Cannot determine controller argument for "App\\Controller\\PromotionController::exportExcel()": the $promotion argument is type-hinted with the non-existent class or interface: "App\\Entity\\Promotion".'],
            'promotionRepository' => ['privates', '.errored.e1UlfF9', NULL, 'Cannot determine controller argument for "App\\Controller\\PromotionController::exportExcel()": the $promotionRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PromotionRepository".'],
        ], [
            'promotion' => '?',
            'promotionRepository' => '?',
        ]);
    }
}
