<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncryptEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpecShaper\EncryptBundle\Subscribers\EncryptEventSubscriber' shared autowired service.
     *
     * @return \SpecShaper\EncryptBundle\Subscribers\EncryptEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/specshaper/encrypt-bundle/Subscribers/EncryptEventSubscriber.php';

        $a = ($container->privates['SpecShaper\\EncryptBundle\\Encryptors\\EncryptorInterface'] ?? $container->getEncryptorInterfaceService());

        if (isset($container->privates['SpecShaper\\EncryptBundle\\Subscribers\\EncryptEventSubscriber'])) {
            return $container->privates['SpecShaper\\EncryptBundle\\Subscribers\\EncryptEventSubscriber'];
        }

        return $container->privates['SpecShaper\\EncryptBundle\\Subscribers\\EncryptEventSubscriber'] = new \SpecShaper\EncryptBundle\Subscribers\EncryptEventSubscriber($a, false);
    }
}
