<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenKeyCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpecShaper\EncryptBundle\Command\GenKeyCommand' shared autowired service.
     *
     * @return \SpecShaper\EncryptBundle\Command\GenKeyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/specshaper/encrypt-bundle/Command/GenKeyCommand.php';

        $container->privates['SpecShaper\\EncryptBundle\\Command\\GenKeyCommand'] = $instance = new \SpecShaper\EncryptBundle\Command\GenKeyCommand();

        $instance->setName('encrypt:genkey');

        return $instance;
    }
}
