<?php

namespace ContainerMtxaxbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionTestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PromotionTestController' shared autowired service.
     *
     * @return \App\Controller\PromotionTestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PromotionTestController.php';

        $container->services['App\\Controller\\PromotionTestController'] = $instance = new \App\Controller\PromotionTestController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\PromotionTestController', $container));

        return $instance;
    }
}
