<?php

namespace ContainerQAv9muj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5GuNpaYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5GuNpaY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5GuNpaY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotion' => ['privates', '.errored..service_locator.5GuNpaY.App\\Entity\\Promotion', NULL, 'Cannot autowire service ".service_locator.5GuNpaY": it needs an instance of "App\\Entity\\Promotion" but this type has been excluded in "config/services.yaml".'],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
        ], [
            'promotion' => 'App\\Entity\\Promotion',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
        ]);
    }
}
