<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SwgBqhQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.swgBqhQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.swgBqhQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blocRepository' => ['privates', 'App\\Repository\\SkillBlocRepository', 'getSkillBlocRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'promotion' => ['privates', '.errored.Pi8fe5u', NULL, 'Cannot determine controller argument for "App\\Controller\\StudentController::choiceSave()": the $promotion argument is type-hinted with the non-existent class or interface: "App\\Entity\\Promotion".'],
            'student' => ['privates', '.errored..service_locator.swgBqhQ.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.swgBqhQ": it needs an instance of "App\\Entity\\Student" but this type has been excluded in "config/services.yaml".'],
            'ueRepository' => ['privates', 'App\\Repository\\UeRepository', 'getUeRepositoryService', true],
        ], [
            'blocRepository' => 'App\\Repository\\SkillBlocRepository',
            'em' => '?',
            'promotion' => '?',
            'student' => 'App\\Entity\\Student',
            'ueRepository' => 'App\\Repository\\UeRepository',
        ]);
    }
}
