<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G5JadJRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G5JadJR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G5JadJR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'promotionRepository' => ['privates', '.errored.ECqJpNN', NULL, 'Cannot determine controller argument for "App\\Controller\\StudentController::edit()": the $promotionRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PromotionRepository".'],
            'student' => ['privates', '.errored..service_locator.G5JadJR.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.G5JadJR": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'promotionRepository' => '?',
            'student' => 'App\\Entity\\User',
            'studentRepository' => 'App\\Repository\\StudentRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
