<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9jP07PHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9jP07PH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9jP07PH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ue' => ['privates', '.errored..service_locator.9jP07PH.App\\Entity\\Ue', NULL, 'Cannot autowire service ".service_locator.9jP07PH": it needs an instance of "App\\Entity\\Ue" but this type has been excluded in "config/services.yaml".'],
            'ueRepository' => ['privates', 'App\\Repository\\UeRepository', 'getUeRepositoryService', true],
        ], [
            'ue' => 'App\\Entity\\Ue',
            'ueRepository' => 'App\\Repository\\UeRepository',
        ]);
    }
}
