<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F_7YHB9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F.7YHB9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F.7YHB9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encryptor' => ['privates', 'SpecShaper\\EncryptBundle\\Encryptors\\EncryptorInterface', 'getEncryptorInterfaceService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'promotion' => ['privates', '.errored.75Ycn20', NULL, 'Cannot determine controller argument for "App\\Controller\\StudentController::sendEmail()": the $promotion argument is type-hinted with the non-existent class or interface: "App\\Entity\\Promotion".'],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'encryptor' => 'SpecShaper\\EncryptBundle\\Encryptors\\EncryptorInterface',
            'mailer' => '?',
            'promotion' => '?',
            'studentRepository' => 'App\\Repository\\StudentRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
