<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HWdwImSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hWdwImS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hWdwImS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bloc' => ['privates', '.errored..service_locator.hWdwImS.App\\Entity\\SkillBloc', NULL, 'Cannot autowire service ".service_locator.hWdwImS": it needs an instance of "App\\Entity\\SkillBloc" but this type has been excluded in "config/services.yaml".'],
            'blocRepository' => ['privates', 'App\\Repository\\SkillBlocRepository', 'getSkillBlocRepositoryService', true],
        ], [
            'bloc' => 'App\\Entity\\SkillBloc',
            'blocRepository' => 'App\\Repository\\SkillBlocRepository',
        ]);
    }
}
