<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YbDKtARService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YbDKtAR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YbDKtAR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'parcour' => ['privates', '.errored..service_locator.YbDKtAR.App\\Entity\\Parcour', NULL, 'Cannot autowire service ".service_locator.YbDKtAR": it needs an instance of "App\\Entity\\Parcour" but this type has been excluded in "config/services.yaml".'],
        ], [
            'parcour' => 'App\\Entity\\Parcour',
        ]);
    }
}
