<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineEncryptSubscriberInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpecShaper\EncryptBundle\Subscribers\DoctrineEncryptSubscriberInterface' shared autowired service.
     *
     * @return \SpecShaper\EncryptBundle\Subscribers\DoctrineEncryptSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/src/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/specshaper/encrypt-bundle/Subscribers/DoctrineEncryptSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/specshaper/encrypt-bundle/Subscribers/DoctrineEncryptSubscriber.php';

        $a = ($container->privates['SpecShaper\\EncryptBundle\\Encryptors\\EncryptorInterface'] ?? $container->getEncryptorInterfaceService());

        if (isset($container->privates['SpecShaper\\EncryptBundle\\Subscribers\\DoctrineEncryptSubscriberInterface'])) {
            return $container->privates['SpecShaper\\EncryptBundle\\Subscribers\\DoctrineEncryptSubscriberInterface'];
        }

        return $container->privates['SpecShaper\\EncryptBundle\\Subscribers\\DoctrineEncryptSubscriberInterface'] = new \SpecShaper\EncryptBundle\Subscribers\DoctrineEncryptSubscriber(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService()), $a, $container->parameters['spec_shaper_encrypt.annotation_classes'], false);
    }
}
