<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParcour2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QD1nIwg.App\Entity\Parcour' shared service.
     *
     * @return \App\Entity\Parcour
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QD1nIwg": it needs an instance of "App\\Entity\\Parcour" but this type has been excluded in "config/services.yaml".');
    }
}
