<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStudentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hDNOYOX.App\Entity\Student' shared service.
     *
     * @return \App\Entity\Student
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hDNOYOX": it needs an instance of "App\\Entity\\Student" but this type has been excluded in "config/services.yaml".');
    }
}
