<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UeType' shared autowired service.
     *
     * @return \App\Form\UeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UeType.php';

        return $container->privates['App\\Form\\UeType'] = new \App\Form\UeType();
    }
}
