<?php

namespace ContainerRB67UBd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9jP07PH.App\Entity\Ue' shared service.
     *
     * @return \App\Entity\Ue
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9jP07PH": it needs an instance of "App\\Entity\\Ue" but this type has been excluded in "config/services.yaml".');
    }
}
