<?php

namespace ContainerQAQ6TXj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XI4fnw4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xI4fnw4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xI4fnw4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\PromotionController::delete' => ['privates', '.service_locator.5GuNpaY', 'get_ServiceLocator_5GuNpaYService', true],
            'App\\Controller\\PromotionController::edit' => ['privates', '.service_locator.5GuNpaY', 'get_ServiceLocator_5GuNpaYService', true],
            'App\\Controller\\PromotionController::index' => ['privates', '.service_locator.gGA2khr', 'get_ServiceLocator_GGA2khrService', true],
            'App\\Controller\\PromotionController::new' => ['privates', '.service_locator.gGA2khr', 'get_ServiceLocator_GGA2khrService', true],
            'App\\Controller\\PromotionController::show' => ['privates', '.service_locator.4lf9RTo', 'get_ServiceLocator_4lf9RToService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\PromotionController:delete' => ['privates', '.service_locator.5GuNpaY', 'get_ServiceLocator_5GuNpaYService', true],
            'App\\Controller\\PromotionController:edit' => ['privates', '.service_locator.5GuNpaY', 'get_ServiceLocator_5GuNpaYService', true],
            'App\\Controller\\PromotionController:index' => ['privates', '.service_locator.gGA2khr', 'get_ServiceLocator_GGA2khrService', true],
            'App\\Controller\\PromotionController:new' => ['privates', '.service_locator.gGA2khr', 'get_ServiceLocator_GGA2khrService', true],
            'App\\Controller\\PromotionController:show' => ['privates', '.service_locator.4lf9RTo', 'get_ServiceLocator_4lf9RToService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\PromotionController::delete' => '?',
            'App\\Controller\\PromotionController::edit' => '?',
            'App\\Controller\\PromotionController::index' => '?',
            'App\\Controller\\PromotionController::new' => '?',
            'App\\Controller\\PromotionController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\PromotionController:delete' => '?',
            'App\\Controller\\PromotionController:edit' => '?',
            'App\\Controller\\PromotionController:index' => '?',
            'App\\Controller\\PromotionController:new' => '?',
            'App\\Controller\\PromotionController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
