<?php

namespace ContainerQAQ6TXj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4lf9RTo.App\Entity\Promotion' shared service.
     *
     * @return \App\Entity\Promotion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4lf9RTo": it needs an instance of "App\\Entity\\Promotion" but this type has been excluded in "config/services.yaml".');
    }
}
